#
#       Set CAN-FD pins:
#
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]

set_property IOSTANDARD LVCMOS18 [get_ports CANFD*_PHY_*]
set_property SLEW FAST [get_ports CANFD*_PHY_TX]
set_property PULLUP true [get_ports CANFD*_PHY_*]

set_property PACKAGE_PIN D4 [get_ports CANFD0_PHY_RX]
set_property PACKAGE_PIN C4 [get_ports CANFD0_PHY_TX]

set_property PACKAGE_PIN G1 [get_ports CANFD1_PHY_RX]
set_property PACKAGE_PIN F1 [get_ports CANFD1_PHY_TX]

set_property PACKAGE_PIN D7 [get_ports CANFD2_PHY_RX]
set_property PACKAGE_PIN D6 [get_ports CANFD2_PHY_TX]



#
#       TX and RX physical pins should be asynchronous for the CAN protocol.
#       Further, number of clock cycles between TX and RX are compensated for in software.
#
set_false_path -to [get_ports CANFD*_PHY_TX]
set_false_path -from [get_ports CANFD*_PHY_RX]

#
#       Timing Constraints for CAN-FD Cores
#       NOTE: Copied from IP Autogenerated constraints.
#set_false_path -to [get_pins -of [get_cells -hier -filter name=~*cdc_to*] -filter {REF_PIN_NAME == D}]
#set_false_path -to [get_pins -of [get_cells -hier -filter name=~*cdc_tig*] -filter {REF_PIN_NAME == D}]
#set_false_path -from  [get_cells -hierarchical -filter {NAME =~ *can_inst/*/IC_REG*BTR*reg[*]}]
#set_false_path -from  [get_cells -hierarchical -filter {NAME =~ *can_inst/*/IC_REG*BRP*reg[*]}]
#set_false_path -from  [get_cells -hierarchical -filter {NAME =~ *can_inst/*/*/ID_FOR_MATCH*reg[*]}]
#set_false_path -to    [get_pins -of [get_cells -hier -filter name=~*IC_REG_ECR*] -filter {REF_PIN_NAME == D}]
#set_false_path -to [get_pins -of [get_cells -hier -filter name=~*can_inst/ol*/*IC_REG_TSR_I*] -filter {REF_PIN_NAME == D}]
#set_false_path -to [get_pins -of [get_cells -hier -filter name=~*can_inst/ol*/*IC_REG_SR_TDCV_I*] -filter {REF_PIN_NAME == D}]

set_property IOSTANDARD LVCMOS33 [get_ports UART_1_*]
set_property PULLUP false [get_ports UART_1_*]
set_property SLEW FAST [get_ports UART_1_*]
set_property OFFCHIP_TERM NONE [get_ports UART_1_*]


set_property PACKAGE_PIN AH14 [get_ports UART_1_rxd]
set_property PACKAGE_PIN AG14 [get_ports UART_1_txd]

#
#       General Purpose Input/Output pins
#
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_tri_io[*]}]
set_property DRIVE 12 [get_ports {GPIO_tri_io[*]}]

# Outputs
#  - UART0_DE
#  - ACTIVATE_LATCH
#  - WATCHDOG_OUT
#  - ACTIVATE_TS
#  - EBS_ENGAGE
#  - ASB_ENGAGE
#  - ASSI_YELLOW
#  - ASSI_BLUE
#  - SYNC_OUT
set_property PACKAGE_PIN W11 [get_ports {GPIO_tri_io[17]}]
set_property PACKAGE_PIN Y9 [get_ports {GPIO_tri_io[16]}]
set_property PACKAGE_PIN E12 [get_ports {GPIO_tri_io[15]}]
set_property PACKAGE_PIN D10 [get_ports {GPIO_tri_io[14]}]
set_property PACKAGE_PIN AC11 [get_ports {GPIO_tri_io[13]}]
set_property PACKAGE_PIN AB11 [get_ports {GPIO_tri_io[12]}]
set_property PACKAGE_PIN AC13 [get_ports {GPIO_tri_io[11]}]
set_property PACKAGE_PIN AC14 [get_ports {GPIO_tri_io[10]}]
set_property PACKAGE_PIN AE14 [get_ports {GPIO_tri_io[9]}]

# Inputs
#  - GPS_PPS
#  - SDC_STATUS
#  - WATCHDOG_STATUS
#  - LATCH_STATUS
#  - ASMS_ON
#  - ASMS_ACTUALLY_ON
#  - EBS_CHECK
#  - ASB_CHECK
#  - SYNC_IN
set_property PACKAGE_PIN AE13 [get_ports {GPIO_tri_io[8]}]
set_property PACKAGE_PIN D11 [get_ports {GPIO_tri_io[7]}]
set_property PACKAGE_PIN E10 [get_ports {GPIO_tri_io[6]}]
set_property PACKAGE_PIN AH13 [get_ports {GPIO_tri_io[5]}]
set_property PACKAGE_PIN AG13 [get_ports {GPIO_tri_io[4]}]
set_property PACKAGE_PIN AF13 [get_ports {GPIO_tri_io[3]}]
set_property PACKAGE_PIN W10 [get_ports {GPIO_tri_io[2]}]
set_property PACKAGE_PIN AA8 [get_ports {GPIO_tri_io[1]}]
set_property PACKAGE_PIN AC12 [get_ports {GPIO_tri_io[0]}]



set_property PULLDOWN true [get_ports {GPIO_tri_io[13]}]
set_property PULLDOWN true [get_ports {GPIO_tri_io[12]}]
set_property PULLDOWN true [get_ports {GPIO_tri_io[8]}]
set_property PULLDOWN true [get_ports {GPIO_tri_io[7]}]
set_property PULLDOWN true [get_ports {GPIO_tri_io[1]}]
set_property PULLDOWN true [get_ports {GPIO_tri_io[0]}]

set_property PACKAGE_PIN AB15 [get_ports {GPIO_tri_io[24]}]
set_property PACKAGE_PIN AG14 [get_ports {GPIO_tri_io[23]}]
set_property PACKAGE_PIN AD14 [get_ports {GPIO_tri_io[22]}]
set_property PACKAGE_PIN AD15 [get_ports {GPIO_tri_io[21]}]
set_property PACKAGE_PIN AA13 [get_ports {GPIO_tri_io[19]}]
set_property PACKAGE_PIN AB13 [get_ports {GPIO_tri_io[20]}]
set_property PACKAGE_PIN AB14 [get_ports {GPIO_tri_io[18]}]

set_property OFFCHIP_TERM NONE [get_ports CANFD0_PHY_TX]
set_property OFFCHIP_TERM NONE [get_ports CANFD1_PHY_TX]
set_property OFFCHIP_TERM NONE [get_ports CANFD2_PHY_TX]
set_property OFFCHIP_TERM NONE [get_ports UART_1_dtrn]
set_property OFFCHIP_TERM NONE [get_ports UART_1_rtsn]
